version: '3.4'

services:
  inventur:
    image: nilsbmedia/ez-inventur:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5436:5436
